package:
  name: pkg_rhel7
  version: "0.0.1"

source:
  git_rev: 
  git_url: https://github.com/monarin/packaging_tutorial.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports: 
    - example_pkg

about:
  home: https://github.com/monarin/packaging_tutorial
