{% set version = '3.0.1a0' %}

package:
  name: mpi4py
  version: {{ version }}

source:
  git_url: https://github.com/mpi4py/mpi4py.git
  git_rev: master

build: 
  # number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  number: 34
requirements:
  build:
    - python
    - cython >=0.22
    - openmpi >=4.0.0

  run:
    - python
    - openmpi >=4.0.0

